title: "Tinkerer"
description: "A modern Magic: The Gathering format built around experimentation."
url: "https://ravaat.github.io"
baseurl: ""

markdown: kramdown

plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
