title: "Tinkerer format"
description: "The official Tinkerer banlist"
url: "Ravaat.github.io"
baseurl: "Ravaat.github.io"

markdown: kramdown

plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
